# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JoinWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JoinWindow(object):
    def setupUi(self, JoinWindow):
        JoinWindow.setObjectName("JoinWindow")
        JoinWindow.resize(800, 480)
        JoinWindow.setStyleSheet("")
        self.centralwidget_join = QtWidgets.QWidget(JoinWindow)
        self.centralwidget_join.setObjectName("centralwidget_join")
        self.label_join_main = QtWidgets.QLabel(self.centralwidget_join)
        self.label_join_main.setGeometry(QtCore.QRect(-1, -1, 800, 480))
        self.label_join_main.setStyleSheet("background-image: url(:/newPrefix/image/juicebro.jpg);")
        self.label_join_main.setText("")
        self.label_join_main.setObjectName("label_join_main")
        self.label_id = QtWidgets.QLabel(self.centralwidget_join)
        self.label_id.setGeometry(QtCore.QRect(130, 130, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(121, 11, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 11, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_id.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("한컴 바겐세일 M")
        font.setPointSize(24)
        self.label_id.setFont(font)
        self.label_id.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id.setObjectName("label_id")
        self.label_phone = QtWidgets.QLabel(self.centralwidget_join)
        self.label_phone.setGeometry(QtCore.QRect(90, 300, 231, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(121, 11, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 11, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_phone.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("한컴 바겐세일 M")
        font.setPointSize(24)
        self.label_phone.setFont(font)
        self.label_phone.setAlignment(QtCore.Qt.AlignCenter)
        self.label_phone.setObjectName("label_phone")
        self.label_sex = QtWidgets.QLabel(self.centralwidget_join)
        self.label_sex.setGeometry(QtCore.QRect(180, 210, 131, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(121, 11, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 11, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_sex.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("한컴 바겐세일 M")
        font.setPointSize(24)
        self.label_sex.setFont(font)
        self.label_sex.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sex.setObjectName("label_sex")
        self.radioButton_man = QtWidgets.QRadioButton(self.centralwidget_join)
        self.radioButton_man.setGeometry(QtCore.QRect(340, 230, 70, 40))
        font = QtGui.QFont()
        font.setFamily("한컴 바겐세일 M")
        font.setPointSize(20)
        self.radioButton_man.setFont(font)
        self.radioButton_man.setObjectName("radioButton_man")
        self.radioButton_woman = QtWidgets.QRadioButton(self.centralwidget_join)
        self.radioButton_woman.setGeometry(QtCore.QRect(440, 230, 70, 40))
        font = QtGui.QFont()
        font.setFamily("한컴 바겐세일 M")
        font.setPointSize(20)
        self.radioButton_woman.setFont(font)
        self.radioButton_woman.setObjectName("radioButton_woman")
        self.label_text = QtWidgets.QLabel(self.centralwidget_join)
        self.label_text.setGeometry(QtCore.QRect(160, 40, 471, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(121, 11, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 11, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("한컴 바겐세일 M")
        font.setPointSize(28)
        self.label_text.setFont(font)
        self.label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text.setObjectName("label_text")
        self.pushButton_join_next = QtWidgets.QPushButton(self.centralwidget_join)
        self.pushButton_join_next.setGeometry(QtCore.QRect(650, 350, 140, 120))
        self.pushButton_join_next.setStyleSheet("border-image: url(:/newPrefix/image/next.png);")
        self.pushButton_join_next.setText("")
        self.pushButton_join_next.setObjectName("pushButton_join_next")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget_join)
        self.lineEdit_id.setGeometry(QtCore.QRect(330, 130, 341, 71))
        font = QtGui.QFont()
        font.setFamily("한컴 바겐세일 M")
        font.setPointSize(20)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.lineEdit_phone = QtWidgets.QLineEdit(self.centralwidget_join)
        self.lineEdit_phone.setGeometry(QtCore.QRect(330, 300, 341, 71))
        font = QtGui.QFont()
        font.setFamily("한컴 바겐세일 M")
        font.setPointSize(20)
        self.lineEdit_phone.setFont(font)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        JoinWindow.setCentralWidget(self.centralwidget_join)

        self.retranslateUi(JoinWindow)
        QtCore.QMetaObject.connectSlotsByName(JoinWindow)

    def retranslateUi(self, JoinWindow):
        _translate = QtCore.QCoreApplication.translate
        JoinWindow.setWindowTitle(_translate("JoinWindow", "MainWindow"))
        self.label_id.setText(_translate("JoinWindow", "닉네임 : "))
        self.label_phone.setText(_translate("JoinWindow", "전화번호 : "))
        self.label_sex.setText(_translate("JoinWindow", "성별 : "))
        self.radioButton_man.setText(_translate("JoinWindow", "남"))
        self.radioButton_woman.setText(_translate("JoinWindow", "여"))
        self.label_text.setText(_translate("JoinWindow", "<회원가입 정보>"))

import xz_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JoinWindow = QtWidgets.QMainWindow()
    ui = Ui_JoinWindow()
    ui.setupUi(JoinWindow)
    JoinWindow.show()
    sys.exit(app.exec_())

